# Generated by Django 5.2.7 on 2025-11-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_incomecategory_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
    ]
