# Generated by Django 5.2.7 on 2025-11-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_remove_income_category_remove_income_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
